### ISSUE TITLE
make issues

### ISSUE THREAD

**Issue by flamedodger** [huguesb/ac2mqtt#1]
Hi,
Home Assistant Supervised
Raspberry Pi4
I installed make using apk I thinnk it has a path issue;

➜  ~ cd /config/ac2mqtt-main

➜  ac2mqtt-main make
go build -o ac2mqtt cmd/ac2mqtt/main.go
make: go: No such file or directory
make: *** [Makefile:2: build] Error 127
➜  ac2mqtt-main

**Comment by huguesb** [comment]
You need the go toolchain (version 1.18 or newer) to be able to compile the program.

I have updated the README to clarify.
